name: Deploy Backend to Heroku

on:
  push:
    branches: [main]
    paths:
      - 'server/**'   # only trigger if /server changes

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24'
      - run: |
          cd server
          npm install
          npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
                    
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Deploy to Heroku (Backend)
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "server"
