name: Deploy Frontend to Heroku

on:
  push:
    branches: [main]
    paths:
      - 'admin/**'   # only trigger if /admin changes

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24'
      - run: |
          cd admin
          npm install
          npm run build

        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_SOCKET_URL: ${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
          
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Deploy to Heroku (Frontend)
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "admin"
